language: c

compiler: gcc

before_install:
    - sudo pip install cpp-coveralls

script: make tests

after_success:
    - coveralls -E '.*\.h' -E '.*test.*' -e third_party --gcov-options=--preserve-paths -b .
